env:
  - PROTOBUF_VERSION=3.1.0

before_install:
  - ./install-godeps.sh
  - ./install-protobuf.sh
  - PATH=/home/travis/bin:$PATH protoc --version

script:
  - PATH=/home/travis/bin:$PATH make all

language: go

go:
  - 1.7
